application: owlection
version: beta
module: default
runtime: python27
api_version: 1
threadsafe: yes

instance_class: F1

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:

- url: /static
  static_dir: static

- url: /admin/.*
  script: controllers.admin.app

- url: /vote.*
  script: controllers.vote.app

- url: /authenticate/.*
  script: controllers.authenticate.app

- url: /intern/.*
  script: controllers.intern.app

- url: /tasks/.*
  script: controllers.tasks.app
  login: admin

- url: /api/.*
  script: controllers.api.app

# Angular2 Frontend
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/dist/\1
  upload: static/dist/(.*\.js)

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/dist/\1
  upload: static/dist/(.*\.css)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/dist/\1
  upload: static/dist/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /.*
#  script: main.app
  static_files: static/dist/index.html
  upload: static/dist/index.html
