application: owlection
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /vote
  script: vote.app

- url: /cast-ballot
  script: castballot.app

- url: /create-election
  script: createelection.app

- url: /login-response
  script: authentication.app

- url: /logout
  script: authentication.app

- url: /logout-response
  script: authentication.app

- url: /cleanup-sessions
  script: cleanupsessions.app

- url: /view-results
  script: viewresults.app

- url: /tasks/.*
  script: tasks.app
  login: admin

- url: /.*
  script: main.app